"""empty message

Revision ID: 9d4fc2473b46
Revises: 9dfdda56b14e
Create Date: 2025-04-23 21:46:25.290447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4fc2473b46'
down_revision = '9dfdda56b14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.drop_constraint('fav_starship_starship_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_starship_starship_id_fkey', 'planet', ['starship_id'], ['id'])

    # ### end Alembic commands ###
