"""empty message

Revision ID: 9dfdda56b14e
Revises: d0ed591785a3
Create Date: 2025-04-21 00:23:43.739120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfdda56b14e'
down_revision = 'd0ed591785a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.drop_constraint('fav_starship_starship_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['starship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_starship_starship_id_fkey', 'starship', ['starship_id'], ['id'])

    # ### end Alembic commands ###
